## Example Config file
baseURL: "https://example.com"
theme: "terminalcv"
title: "terminalcv"

params:
  version: '2.0.0'
  description: "My terminal cv"
  prompt:
    core:
      text: "user@terminalCV"
      color: 'pink'
      before: '['
      beforeColor: 'red'
      after: '\]'
      afterColor: 'red'
      # separator: '-'
    separator:
      text: "-"
      # color: 
    path: 
      before: '['
      beforeColor: 'red'
      text: '~/terminalcv'
      color: 'blue'
      after: '\]'
      afterColor: 'red'
    extra:
      text: ": "
      color: 'orange'

  # promptColor: grey
  # promptSimbols: ":~$"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # useLess: true
  exitLocation: 'about:blank'
  source: true
  #use a ‎ (blank character) if your first character of the ascii art is a whitespace
  greeting: | 
    ‎ _                      _             _  _______      __
    | |                    (_)           | |/ ____\ \    / /
    | |_ ___ _ __ _ __ ___  _ _ __   __ _| | |     \ \  / / 
    | __/ _ \ '__| '_ ` _ \| | '_ \ / _` | | |      \ \/ /  
    | ||  __/ |  | | | | | | | | | | (_| | | |____   \  /   
     \__\___|_|  |_| |_| |_|_|_| |_|\__,_|_|\_____|   \/

    Welcome to my online resume

    Type 'help' for a list of available commands


  whois: 
    # settings:
    #   useLess: true
    details:
      name: "John Doe"
      profession: "Unknown"
      location: "Somewhere"
      email: "foo@someemail.com"
      homelink: "https://myHomePage.com"
      description: |
              Here you can write something catchy about yourself

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
    - name: "github"
      url: "https://github.com"
    - name: "facebook"
      url: "https://facebook.com"
    - name: "myspace"
      url: "https://myspace.com"
    - name: "hi5"
      url: "https://www.hi5.com"
    - name: "instagram"
      url: "https://instagram.com"
    - name: "Another social"
      url: "https://anothersocial.com"

  work:
    # settings:
    #   useLess: true
    details:
    - jobTitle: Job With Red Title
      color: red
      company: '-' 
      location: somewhere
      date: August 2010 - Present
      description: Some description about this red title job

    - jobTitle: Job with purple title
      color: purple
      company: '-'
      location: somewhere elese
      date: July 2000  - July 2010
      description: Some description about this purple job

    - jobTitle: Job with default color title
      company: '-'
      location: anywhere
      date: July 2008 - 2010
      description: Description about this default color job

  education:
    details:
    - courseName: Red Color training
      color: red
      date: June 2019 - July 2019
      description: Descrption about red color trianing

    - courseName: Default color training
      date: Sept 2004 - Jun 2008
      #description: There is no need for description

  skills:
    settings:
      useLess: true
    details:
    - name: Skill 1
      percentage: 90
      Description: you can add a description

    - name: Skill 2
      percentage: 30
      #description: or you can leave it comented   

    - name: Skill 3
      color: blue
      percentage: 50
      description: Skill names can have colors too

  softskills:
    # settings:
    #   useLess: true
    details:
    - name: SoftSkill 1
      color: red
      percentage: 80
      #description:

    - name:  SoftSkill 2
      #color: 
      percentage: 90
      description: Description

  languages:
    # settings:
    #   useLess: true
    details:
    - name: English
      color: Blue
      percentage: 50
      #description: 

    - name: Gibberish
      percentage: 100
      description: pasghettipigglywiggly


  projects:
    # settings:
    #   useLess: true
    details:
    - title: Project Red
      color: red
      date: since 2019
      link: https://example.com
      description: Describing red stuff

    - title: Project Blue
      color: blue
      date: since 2016
      link: https://example.com/blue
      #description: nothing to describe

    - title: Project Default
      date: Since 2017
      link: https://example.com/default
      #description: not there either

  certifications:
    # settings:
    #   useLess: true
    details:
    - certName: Example Cert
      company: Example Certifying Company
      date: Date of Completion
      badge: https://www.link.to.badge
      #description: Lorem Ipsum
  
  misc: 
    # settings:
    #   useLess: true
    commandName: newcommand
    title: "This Section can have a different command name"
    titleColor: teal
    content: |
          Here the title and the content can have different colors
          The content can be multi
          
          line

          And spaces       will be respected as well
          This section will have the default command: misc
          but you can name it something else with the property
          commandName: <String>
          Give it a shot and try and uncomment the line 
          commandName: newcommand
          now instead of misc you can execute the newcommand for this section
          Auto completion will know it too! :D 

    contentColor: orange
